/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY */

/*
 * schema-defined QAPI visitor functions
 *
 * Copyright IBM, Corp. 2011
 *
 * Authors:
 *  Anthony Liguori   <aliguori@us.ibm.com>
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 *
 */

#include "qapi-visit.h"

void visit_type_NameInfo(Visitor *m, NameInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "NameInfo", name, sizeof(NameInfo), errp);
    visit_start_optional(m, (obj && *obj) ? &(*obj)->has_name : NULL, "name", errp);
    if ((*obj)->has_name) {
        visit_type_str(m, (obj && *obj) ? &(*obj)->name : NULL, "name", errp);
    }
    visit_end_optional(m, errp);
    visit_end_struct(m, errp);
}

void visit_type_NameInfoList(Visitor *m, NameInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        NameInfoList *native_i = (NameInfoList *)i;
        visit_type_NameInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_VersionInfo(Visitor *m, VersionInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "VersionInfo", name, sizeof(VersionInfo), errp);
    visit_start_struct(m, NULL, "", "qemu", 0, errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->qemu.major : NULL, "major", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->qemu.minor : NULL, "minor", errp);
    visit_type_int(m, (obj && *obj) ? &(*obj)->qemu.micro : NULL, "micro", errp);
    visit_end_struct(m, errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->package : NULL, "package", errp);
    visit_end_struct(m, errp);
}

void visit_type_VersionInfoList(Visitor *m, VersionInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        VersionInfoList *native_i = (VersionInfoList *)i;
        visit_type_VersionInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_KvmInfo(Visitor *m, KvmInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "KvmInfo", name, sizeof(KvmInfo), errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->enabled : NULL, "enabled", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->present : NULL, "present", errp);
    visit_end_struct(m, errp);
}

void visit_type_KvmInfoList(Visitor *m, KvmInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        KvmInfoList *native_i = (KvmInfoList *)i;
        visit_type_KvmInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_RunState(Visitor *m, RunState * obj, const char *name, Error **errp)
{
    visit_type_enum(m, (int *)obj, RunState_lookup, "RunState", name, errp);
}

void visit_type_StatusInfo(Visitor *m, StatusInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "StatusInfo", name, sizeof(StatusInfo), errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->running : NULL, "running", errp);
    visit_type_bool(m, (obj && *obj) ? &(*obj)->singlestep : NULL, "singlestep", errp);
    visit_type_RunState(m, (obj && *obj) ? &(*obj)->status : NULL, "status", errp);
    visit_end_struct(m, errp);
}

void visit_type_StatusInfoList(Visitor *m, StatusInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        StatusInfoList *native_i = (StatusInfoList *)i;
        visit_type_StatusInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_UuidInfo(Visitor *m, UuidInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "UuidInfo", name, sizeof(UuidInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->UUID : NULL, "UUID", errp);
    visit_end_struct(m, errp);
}

void visit_type_UuidInfoList(Visitor *m, UuidInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        UuidInfoList *native_i = (UuidInfoList *)i;
        visit_type_UuidInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_ChardevInfo(Visitor *m, ChardevInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "ChardevInfo", name, sizeof(ChardevInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->label : NULL, "label", errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->filename : NULL, "filename", errp);
    visit_end_struct(m, errp);
}

void visit_type_ChardevInfoList(Visitor *m, ChardevInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        ChardevInfoList *native_i = (ChardevInfoList *)i;
        visit_type_ChardevInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}

void visit_type_CommandInfo(Visitor *m, CommandInfo ** obj, const char *name, Error **errp)
{
    visit_start_struct(m, (void **)obj, "CommandInfo", name, sizeof(CommandInfo), errp);
    visit_type_str(m, (obj && *obj) ? &(*obj)->name : NULL, "name", errp);
    visit_end_struct(m, errp);
}

void visit_type_CommandInfoList(Visitor *m, CommandInfoList ** obj, const char *name, Error **errp)
{
    GenericList *i, **head = (GenericList **)obj;

    visit_start_list(m, name, errp);

    for (*head = i = visit_next_list(m, head, errp); i; i = visit_next_list(m, &i, errp)) {
        CommandInfoList *native_i = (CommandInfoList *)i;
        visit_type_CommandInfo(m, &native_i->value, NULL, errp);
    }

    visit_end_list(m, errp);
}
